"id","type","name"
1,"kind","Panes y masas"
2,"kind","Pastas"
3,"kind","Bizcochos y galletas"
4,"kind","Carnes"
5,"kind","Aves"
6,"kind","Pescados y mariscos"
7,"kind","Ensaladas"
8,"kind","Contenido alcoholico"
9,"kind","Salsas y guarniciones"
10,"kind","Sopas y cremas"
11,"kind","Arroces"
12,"kind","Legumbres y guisos"
13,"kind","Tartas y dulces"
14,"kind","Helados y sorbetes"
15,"kind","Frutas"
16,"kind","Verduras"
17,"kind","Huevos"
18,"kind","Lacteos"
19,"kind","Frutos secos"
20,"kind","Encurtidos y conservas"
21,"kind","Postre"
22,"kind","Bebida"
23,"kind","Primeros platos"
24,"kind","Segundos platos"
25,"kind","Entradas"
26,"kind","Sopas y cremas"
27,"kind","Acompa\~namientos"
28,"kind","Emparedados"
29,"kind","Botana"
30,"kind","Comida rapida"
31,"flavour","Dulce"
32,"flavour","Salado"
33,"flavour","Acido"
34,"flavour","Amargo"
35,"flavour","Umami"
36,"flavour","Picante"
37,"occasion","Halloween"
38,"occasion","Navidad"
39,"occasion","San Valentin"
40,"occasion","Primavera"
41,"occasion","Verano"
42,"occasion","Oto\~no"
43,"occasion","Invierno"
44,"occasion","Desayunos"
45,"occasion","Almuerzos"
46,"occasion","Meriendas"
47,"occasion","Ocasion especial"
48,"region","Italiana"
49,"region","Mediterranea"
50,"region","Asiatica"
51,"region","Mexicana"
52,"region","Americana"
53,"region","Hindu"
54,"region","Francesa"
55,"region","Tailandesa"
56,"region","Cantonesa"
57,"region","Japonesa"
58,"region","China"
59,"region","Medio oriente"
60,"region","Alemana"
61,"region","Argentina"
62,"region","Brasile\~na"
63,"region","Colombiana"
64,"region","Coreana"
65,"region","Cubana"
66,"region","Espa\~nola"
67,"region","Finlandesa"
68,"region","Griega"
69,"region","Holandesa"
70,"region","Indonesa"
71,"region","Portuguesa"
72,"health","Bajas en colesterol"
73,"health","Diabeticos"
74,"health","Sin lactosa"
75,"health","Celiacos"
76,"health","Alergicos"
77,"health","Bajar de peso"
78,"health","Vegetarianos"
79,"temperature","Frio"
80,"temperature","Templado"
81,"temperature","Caliente"
82,"people","Bebes"
83,"people","Ni\~nos"
84,"people","Adultos"
85,"people","Familiares"
86,"people","Adultos mayores"
87,"texture","Liquidas"
88,"texture","Blandas"
89,"texture","Semi-blandas"
90,"texture","Crujientes"
91,"texture","Duras"
