[
{"id":1,"type":"kind","name":"Panes y Masas"},
{"id":2,"type":"kind","name":"Pastas y pizza"},
{"id":3,"type":"kind","name":"Bizcochos y Galletas"},
{"id":4,"type":"kind","name":"Carnes y Aves"},
{"id":5,"type":"kind","name":"Pescados y Mariscos"},
{"id":6,"type":"kind","name":"Ensaladas"},
{"id":7,"type":"kind","name":"Contenido alcoholico"},
{"id":8,"type":"kind","name":"Salsas y Guarniciones"},
{"id":9,"type":"kind","name":"Sopas y Cremas"},
{"id":10,"type":"kind","name":"Arroces"},
{"id":11,"type":"kind","name":"Legumbres y Guisos"},
{"id":12,"type":"kind","name":"Tartas y Dulces"},
{"id":13,"type":"kind","name":"Helados y Sorbetes"},
{"id":14,"type":"kind","name":"Frutas y Otros postres"},
{"id":15,"type":"kind","name":"Huevos y Lacteos"},
{"id":16,"type":"kind","name":"Encurtidos y Conservas"},
{"id":17,"type":"kind","name":"Postre"},
{"id":18,"type":"kind","name":"Bebida"},
{"id":19,"type":"kind","name":"Primeros platos"},
{"id":20,"type":"kind","name":"Segundos platos"},
{"id":21,"type":"kind","name":"Entradas"},
{"id":22,"type":"kind","name":"Sopas"},
{"id":23,"type":"kind","name":"Acompa\~namientos"},
{"id":30,"type":"kind","name":"Botana"},
{"id":31,"type":"flavour","name":"Dulce"},
{"id":32,"type":"flavour","name":"Salado"},
{"id":33,"type":"flavour","name":"Agrio"},
{"id":34,"type":"flavour","name":"Amargo"},
{"id":35,"type":"flavour","name":"Umami"},
{"id":36,"type":"flavour","name":"Grasoso"},
{"id":37,"type":"occasion","name":"Halloween"},
{"id":38,"type":"occasion","name":"Navidad"},
{"id":39,"type":"occasion","name":"San Valentin"},
{"id":40,"type":"occasion","name":"Verano"},
{"id":41,"type":"occasion","name":"Desayunos"},
{"id":42,"type":"occasion","name":"Meriendas"},
{"id":43,"type":"occasion","name":"Ocasion especial"}
{"id":44,"type":"region","name":"Italiana"},
{"id":45,"type":"region","name":"Mediterranea"},
{"id":46,"type":"region","name":"Asiatica"},
{"id":47,"type":"region","name":"Mexicana"},
{"id":48,"type":"region","name":"Americana"},
{"id":49,"type":"region","name":"Hindu"},
{"id":50,"type":"region","name":"Francesa"},
{"id":50,"type":"region","name":"Tailandesa"},
{"id":50,"type":"region","name":"Cantonesa"},
{"id":50,"type":"region","name":"Japonesa"},
{"id":50,"type":"region","name":"China"},
{"id":50,"type":"region","name":"Medio oriente"},
]