"id","type","name"
1,"kind","Panes y masas"
2,"kind","Pastas"
3,"kind","Bizcochos y galletas"
4,"kind","Carnes"
4,"kind","Aves"
5,"kind","Pescados y mariscos"
6,"kind","Ensaladas"
7,"kind","Contenido alcoholico"
8,"kind","Salsas y guarniciones"
9,"kind","Sopas y cremas"
10,"kind","Arroces"
11,"kind","Legumbres y guisos"
12,"kind","Tartas y Dulces"
13,"kind","Helados y Sorbetes"
14,"kind","Frutas y verduras"
15,"kind","Huevos y lacteos"
16,"kind","Encurtidos y conservas"
17,"kind","Postre"
18,"kind","Bebida"
19,"kind","Primeros platos"
20,"kind","Segundos platos"
21,"kind","Entradas"
22,"kind","Sopas y cremas"
24,"kind","Acompa\~namientos"
25,"kind","Emparedados"
26,"kind","Botana"
27,"flavour","Dulce"
28,"flavour","Salado"
29,"flavour","Agrio"
30,"flavour","Amargo"
31,"flavour","Umami"
32,"flavour","Grasoso"
82,"flavour","Picante"
33,"occasion","Halloween"
34,"occasion","Navidad"
35,"occasion","San Valentin"
36,"occasion","Primavera"
37,"occasion","Verano"
38,"occasion","Otono"
39,"occasion","Invierno"
40,"occasion","Desayunos"
41,"occasion","Meriendas"
42,"occasion","Ocasion especial"
43,"region","Italiana"
44,"region","Mediterranea"
45,"region","Asiatica"
46,"region","Mexicana"
47,"region","Americana"
48,"region","Hindu"
49,"region","Francesa"
50,"region","Tailandesa"
51,"region","Cantonesa"
52,"region","Japonesa"
53,"region","China"
54,"region","Medio oriente"
55,"region","Alemana"
56,"region","Argentina"
57,"region","Brasile\~na"
58,"region","Colombiana"
59,"region","Coreana"
60,"region","Cubana"
61,"region","Espa\~nola"
62,"region","Finlandesa"
63,"region","Griega"
64,"region","Holandesa"
65,"region","Indonesa"
66,"region","Portuguesa"
67,"health","Bajas en colesterol"
68,"health","Diabeticos"
69,"health","Sin lactosa"
70,"health","Celiacos"
71,"health","Alergicos"
72,"health","Bajar de peso"
73,"health","Vegetarianos"
74,"temperature","Frio"
75,"temperature","Templado"
76,"temperature","Caliente"
77,"people","Bebes"
78,"people","Ni\~nos"
79,"people","Adultos"
80,"people","Familiares"
81,"people","Adultos mayores"
83,"texture","Liquidas"
84,"texture","Blandas"
85,"texture","Semi-blandas"
86,"texture","Duras"
87,"texture","Crujientes"
